### ISSUE TITLE
Install prometheus using docker

### ISSUE THREAD

**Issue by replicajune** [cloudalchemy/ansible-prometheus#173]
Hi,

I would like to use this role to install prometheus with docker.

From what I can see, it would mean to change some stuff here and there (have a "pre-install" generic task, put some variables here and there to give a choice, etc ..)

Would this be something interesting for your role to have this feature ?

**Comment by paulfantom** [comment]
Personally I don't see any use in this, but maybe someone else has such need :smiley: 

To do this properly it would need to have:
 - parallel `install_docker.yml` tasks file with tasks relevant to containerized installation
 - `install.yml` split into two sections. So it can choose installation method and delegate it to proper file (`install_docker.yml` or `install_binary.yml`) while still allowing to have common parts 
 - new variable to choose installation method.
 - and the hardest part: molecule tests. Since we are already using containers to run each OS test instance it would need to use some sort of docker-in-docker trick.

As you can see this is quite a lot of things to do, but I will be happy to accept a PR and assist when you need some help.

**Comment by paulfantom** [comment]
That is great to hear! :tada: You can create a PR and work on it there, this way I could do reviews as you progress :)

I will be a bit busy till Monday so my responses can be slower than usual.
