### ISSUE TITLE
Prometheus failed to start on Ubuntu 18.04: LimitNOFILE: Operation not permitted

### ISSUE THREAD

**Issue by JordanP** [cloudalchemy/ansible-prometheus#190]
On a fresh Ubuntu 18.04 install: "systemctl start prometheus" fails with 
```
mars 08 12:53:01 ip-172-31-28-36 systemd[8512]: prometheus.service: Failed to adjust resource limit LimitNOFILE: Operation not permitted
mars 08 12:53:01 ip-172-31-28-36 systemd[8512]: prometheus.service: Failed at step LIMITS spawning /usr/local/bin/prometheus: Operation not permitted
```
Any help appreciated :) (beside commenting out `LimitNOFILE=infinity` in the SystemD unit file)
Thanks !

**Comment by paulfantom** [comment]
Could you check two things?
1. What is the output of `ulimit -n` when run by root?
2. Could you set `LimitNOFILE=65535` instead of `LimitNOFILE=infinity` and try starting prometheus service?

**Comment by JordanP** [comment]
Changing to `LimitNOFILE=65535` worked and now the service starts just fine.

`ulimit -n` as root returns `1024574` but that's just the value I've previously set in `/etc/security/limits.conf`

**Comment by paulfantom** [comment]
[systemd option `LimitNOFILE`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties) is trying to set the same limit as `ulimit -n` and since we are setting it here to `infinity` but you capped it in your system to 1024574 then service fails as `infinity` (`unlimited`) is not available.
And it works when you set it to 65535 as this is less than a limit you set in `/etc/security/limits.conf` :)

@SuperQ what do you think about changing this option from `infinity` to sth like `65535`?
