### ISSUE TITLE
Variabilize prometheus system user name

### ISSUE THREAD

**Issue by rgarrigue** [cloudalchemy/ansible-prometheus#246]
Hi there

I'm using your role, and the `create prometheus system user` task is failing. Reason is, I've a "base" playbook installing common stuff, including prometheus exporters. Hence the prometheus user is created beforehand, and used by the prometheus-node-exporter (Debian 10) service, hence usermod doesn't want to touch it.

```
TASK [cloudalchemy.prometheus : create prometheus system user] ********************
fatal: [i-01b805277ba52f9f0]: FAILED! => {"changed": false, "msg": "usermod: user prometheus is currently used by process 26055\n", "name": "prometheus", "rc": 8}

...

root@i-01b805277ba52f9f0:/opt/monitoring# ps -ef | grep 26055
prometh+ 26055     1  0 10:07 ?        00:00:00 /usr/bin/prometheus-node-exporter
root     26551  6613  0 10:08 pts/0    00:00:00 grep 26055
```

I'll solve my issue using a pre-task most likely, but I wish I could just say that the server use a different username.  

Thanks for the role & grafana & altermanager btw :-)

**Comment by paulfantom** [comment]
If you use the same user for `prometheus` and `node-exporter` installed from roles in cloudalchemy, it won't work (as you can see). This is due to a fact, that those users need different home directories and ansible would want to change user settings on every pass but it won't be able to as a process is using that user. Introducing a parametrized username and/or group won't change this logic and it won't fix your issue. From the role perspective, we would need to introduce user management as a feature flag. Unfortunately, such flag creates a hole in secure-by-default approach and can create problems with upgrades (especially when users start to switch this option on and off).

---
We tried to use ansible in a similar way to how packaging works. With such an approach, we created one user per "package" (ansible role) to have a more secure user setting tailored to a specific process. Additionally, we always wanted cloudalchemy roles to enforce security best practices known from CIS and RHEL STIG standards, and for that reason we try to maintain compatibility with https://github.com/dev-sec/ansible-os-hardening ansible role.

---
In the future (when major distros are on systemd version 235 or higher), we might get rid of user management in some roles by using [dynamic user setting from systemd](http://0pointer.net/blog/dynamic-users-with-systemd.html). This could already be done in roles that install processes which don't write data to disk (exporters and alertmanager). Possibly this could also solve your problem. 
I am open to PRs introducing it as a feature.

**Comment by rgarrigue** [comment]
A clarification on your first point, I don't use cloudalchemy's exporters roles. I've a homemade role that install Debian 10 provided packages. And those .deb packages seems to be creating the `prometheus` user your cloudalchemy.prometheus is snatching back.

+1 for the other points.
