### ISSUE TITLE
README: Outdated links to the demo-site repo

### ISSUE THREAD

**Issue by funkyfuture** [cloudalchemy/ansible-prometheus#286]
the README's variables table contains outdated links to the demo site repo, e.g. for `prometheus_targes` it should rather be https://github.com/cloudalchemy/demo-site/blob/64155c8d0fbf24c55a80dae65db7fed650afe848/group_vars/all/vars#L11

but since this affects various and the README itself is up-to-date, maybe you want to change the references generally to reduce maintenance cost. hence i didn't provide a patch.

and many thanks for your efforts!

**Comment by paulfantom** [comment]
Even bettere would be to point to https://github.com/prometheus/demo-site/blob/master/group_vars/prometheus.yml#L34.

This would be nice to fix, could you create a PR?

**Comment by funkyfuture** [comment]
but the referenced lines would be falsified at some point in the future. what about just linking the whole document in the master branch? it's not difficult to find the key(s) in question.

**Comment by paulfantom** [comment]
Sounds good to me.

---

I had a plan to refactor how README.md is structured and use sth like https://github.com/campoy/embedmd to embed examples and provide:
- default values from [defaults/main.yml](https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml)
- example playbooks, like one in [molecule/alternative/playbook.yml](https://github.com/cloudalchemy/ansible-prometheus/blob/master/molecule/alternative/playbook.yml)

With this, I could gather all README.md files from multiple cloudalchemy repos and create a static docs site.

Sadly this never happened due to lack of time :(

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
