### ISSUE TITLE
Would you mind sharing the way your bot works ? 

### ISSUE THREAD

**Issue by rgarrigue** [cloudalchemy/ansible-prometheus#312]
Hi there

The question is related to the way you maintain all your role. I saw you've a bot maintaining good practice pushed on the skeleton. Do you have some source, a blog article, anything about the way you do this that you could share ? I'm very interested in such a thing, maintaining more than a dozen roles here, it's becoming an assle.

And thanks for the good work, I've been using your grafana & prometheus & alertmanager for a while now, it's been great :+1:

**Comment by paulfantom** [comment]
I don't have any written material but fortunately, everything is publicly available in cloudalchemy organization. Maybe I should write something :thinking: 

As to how this works, it can be split into 3 phases:

1) Discovery and sync
2) Testing
3) Auto-merge

#### Discovery and sync

[The first phase is done by travis](https://github.com/cloudalchemy/auto-maintenance/blob/master/.travis.yml) using 2 bash scripts from [cloudalchemy/auto-maintenance](https://github.com/cloudalchemy/auto-maintenance) repository. This is done on a daily basis and those two scrips are:
- [autocommiter.sh](https://github.com/cloudalchemy/auto-maintenance/blob/master/autocommiter.sh) - responsible for checking if there was a new release of the operand (for example prometheus).
- [sync_skeleton.sh](https://github.com/cloudalchemy/auto-maintenance/blob/master/sync_skeleton.sh) - responsible for synchronizing selecten files or part of files across repositories.  It takes [cloudalchemy/skeleton](https://github.com/cloudalchemy/skeleton) repository as a source of truth.

When any change is detected by those scripts, they automatically create a new PR, which is where second phase begins.

#### Testing

Every role in cloudalchemy has an extensive test suite based on molecule, docker, tox, and travis. This ensures that role was run at least once against the last 2-3 ansible versions, on all supported OSes, with the default and alternative variables set. Such a test suite gives me fairly good confidence when everything is green. It also is a bit unified, so all test scenarios are similar.

There is also a post-merge molecule scenario that checks what happens when the `latest` version of the operand was set. This unfortunately cannot be executed on every PR due to github API rate limitations.

#### Auto-merge

When everything was green in CI and PR came from @cloudalchemybot it gets picked up by [mergify](https://github.com/marketplace/mergify) bot and gets automatically merged.


On top of all that, I use:
- [stale bot](https://probot.github.io/apps/stale/) to close old issues (but not PRs!)
- [micnncim/action-label-syncer](https://github.com/micnncim/action-label-syncer) GitHub action to sync labels across repositories
- [paulfantom/periodic-labeler](https://github.com/paulfantom/periodic-labeler) GitHub action to label PRs based on their modified files.
