### ISSUE TITLE
Any plans to migrate to a community collection

### ISSUE THREAD

**Issue by rockaut** [cloudalchemy/ansible-prometheus#313]
Now that 2.10 with collections is a thing are there any plans to migrate to a community.prometheus collection maybe. Imo beside the operational benefits the perception of users into the "name" would be better.

**Comment by paulfantom** [comment]
What do you mean by `community.prometheus`? If a collection was created, it would need to be named sth like `cloudalchemy.prometheus` due to how collections are named in galaxy.

Yes, there were plans to create a collection since collections were introduced over a year ago. However, there is no much operational benefit as we don't use any custom plugins, which means collection would only group roles together. And there is one major problem with a groupping mechanism - what should be included in a group? Should it be just barebone (prometheus + alertmanager) or maybe it should have all exporters from @cloudalchemy organization? If not all exporters then which ones? I know one for sure, grafana shouldn't be included in prometheus collection.

On top of all those concerns I personally don't have time to investigate the topic more and create such a collection. If you want to pick it up, you have my blessing ;)

**Comment by rockaut** [comment]
I meant if it maybe will get an "official" community prometheus repo under https://github.com/ansible-collections
