### ISSUE TITLE
RestrictSUIDSGID not supported in Debian buster

### ISSUE THREAD

**Issue by kmille** [cloudalchemy/ansible-prometheus#324]
Hey,
the systemd unit file contains RestrictSUIDSGID=true. The RestrictSUIDSGID feature came with systemd 242, Debian buster still uses systemd 241 which leads to the following warnings:
Dec 17 09:00:07 hostnamev systemd[1]: /etc/systemd/system/blackbox_exporter.service:24: Unknown lvalue 'RestrictSUIDSGID' in section 'Service', ignoring

valid links are here: https://github.com/cloudalchemy/ansible-blackbox-exporter/issues/75

**Comment by paulfantom** [comment]
We decided against trying to figure out which OS has which systemd version and also against trying to figure out which systemd option was introduced in which version. Since systemd can handle options which are not yet present we decided to provide as secure service file as possible while still making the code readable by avoiding unnecessary conditionals in [service file template](https://github.com/cloudalchemy/ansible-prometheus/blob/master/templates/prometheus.service.j2).
