### ISSUE TITLE
Restrict binary access

### ISSUE THREAD

**Issue by soinu** [cloudalchemy/ansible-prometheus#333]
**What is missing?**

The prometheus and promtool binary have quite open permissions. They, well at least prometheus, should be restricted to the prometheus user

I would suggest changing the owner of them to `prometheus:prometheus` and the permission to 0700.

**Why do we need it?**

If there is every any privilege escalation bug or similar the prometheus binary could be abused for such.

**Comment by SuperQ** [comment]
That's not how privilege escalation works.

* The prometheus binary is not SUID, nor does it have any capabilities.
* Changing the owner to `prometheus` is worse, since a remote attacker could then overwrite the binary.

The current setup, where the binary is owned by root, but run as `prometheus`, is the safest mode of operation.

**Comment by soinu** [comment]
> Changing the owner to prometheus is worse, since a remote attacker could then overwrite the binary.

That's a good point, thank you.
